### ISSUE TITLE
error

### ISSUE THREAD

**Issue by F12Bug** [m-sec-org/EZ#1]
panic: assignment to entry in nil map

goroutine 479316 [running]:
hawkX/pkg/engine.handleRequestPaused(0xc00711d540, 0xc00c7c5800)
        hawkX@v0.0.0/pkg/engine/event_handler.go:73 +0x466
hawkX/pkg/engine.(*Page).HandleEventAndHijack.func2(0x0?)
        hawkX@v0.0.0/pkg/engine/page.go:245 +0x1d
reflect.Value.call({0x24e4540?, 0xc004658c30?, 0x100c0090b5e68?}, {0x2a7b80d, 0x4}, {0xc0090b5f80, 0x1, 0xc00711d540?})
        reflect/value.go:584 +0x8c5
reflect.Value.Call({0x24e4540?, 0xc004658c30?, 0xc00711d540?}, {0xc0090b5f80?, 0x85b02f?, 0xc007e43f90?})
        reflect/value.go:368 +0xbc
github.com/go-rod/rod.(*Browser).eachEvent.func1()
        github.com/go-rod/rod@v0.114.5/browser.go:402 +0x40e
created by hawkX/pkg/engine.(*Page).HandleEventAndHijack
        hawkX@v0.0.0/pkg/engine/page.go:238 +0x3aa

**Comment by nodocx** [comment]
感谢您的反馈，该问题我们已知晓，将于下个版本修复
