### ISSUE TITLE
raw-https 扫描失败

### ISSUE THREAD

**Issue by danielwu182** [m-sec-org/EZ#13]
ez_linux_amd64 -l debug webscan   --pocs "json" --rhs aaa -nff 

[utils.go:1459] please use copyright ez, check your network or proxy!

**Comment by 1oid** [comment]
检查网络环境，系统时间

**Comment by danielwu182** [comment]
如果是--raw  aaa   扫描正常啊

**Comment by 1oid** [comment]
只是光看你 下面这个报错的话是网络问题。x
```
[utils.go:1459] please use copyright ez, check your network or proxy!
```
在使用--raw-https的时候还有其他报错吗

**Comment by danielwu182** [comment]
![image](https://github.com/m-sec-org/EZ/assets/10613104/fc11ebbb-4e75-4bd9-bccf-aba1c754fded)
现在  http和https  debug错误一样了

**Comment by 1oid** [comment]
你数据包里面就是这个 47.114的ip吗，看起来并不是报错，而且请求也是正常的。

**Comment by danielwu182** [comment]
ez_linux_amd64 -l debug webscan   --pocs "json" --raw-https aaa --nff
![image](https://github.com/m-sec-org/EZ/assets/10613104/b5466248-d817-4ab2-afdb-28e2b21e251c)
ez_linux_amd64 -l debug webscan   --pocs "json" --raw aaa --nff 
![image](https://github.com/m-sec-org/EZ/assets/10613104/67cc3eeb-ad67-46d5-af44-7d6c7cc18069)

**Comment by 1oid** [comment]
这样写 `--raw raw.txt --raw-https`

--raw-https是用来说明--raw数据是https，是一个布尔值，默认false
