### ISSUE TITLE
msec注册账号短信收不到

### ISSUE THREAD

**Issue by shen771** [m-sec-org/EZ#15]
msec社区注册，更换多个手机号及朋友手机号，实测均无法收到短信验证码，无法使用此工具，问下这个还维护吗？

**Comment by zitn** [comment]
你好，这个问题经过排查已经解决，请重新尝试，注册后告知一下您的用户名，给您积分奖励

**Comment by shen771** [comment]
可以注册了，但是申请证书图形验证码，即使输入正确，也提示内部错误

![22](https://github.com/user-attachments/assets/a4f817b9-a66f-4195-aee2-135a3f38f7ab)

**Comment by zitn** [comment]
这个问题也解决了，麻烦重新申请一下，不好意思，最近机房网络调整，服务受到一些影响

**Comment by weishikai2346** [comment]
我在注册账号的时候验证码总是显示错误
