### ISSUE TITLE
爬虫报错

### ISSUE THREAD

**Issue by woshinibabao1** [m-sec-org/EZ#18]
[INF] 2024-10-05 23:03:05 [crawler.go:35] [1/1] crawler url:http://www.nanhack.com/
[INFO] 2024/10/05 23:03 use Chrome-Like at: C:\Program Files\Google\Chrome\Application\chrome.exe
[ERRO] 2024/10/05 23:03 navigate timeout URL —— http://www.nanhack.com/: context deadline exceeded
panic: json: cannot unmarshal object into Go struct field NetworkResponseReceivedExtraInfo.cookiePartitionKey of type string

goroutine 46 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0x7ff7b0350d00?, 0xc006e460a0?})
        github.com/go-rod/rod@v0.114.5/lib/utils/utils.go:68 +0x25
github.com/go-rod/rod/lib/utils.E(...)
        github.com/go-rod/rod@v0.114.5/lib/utils/utils.go:74
github.com/go-rod/rod.(*Message).Load(0xc0003a61e0, {0x22b5e1e1768, 0xc002cc0000})
        github.com/go-rod/rod@v0.114.5/utils.go:60 +0x26c
github.com/go-rod/rod.(*Browser).eachEvent.func1()
        github.com/go-rod/rod@v0.114.5/browser.go:397 +0x237
created by hawkX/pkg/engine.(*Page).HandleEventAndHijack
        hawkX@v0.0.0/pkg/engine/page.go:238 +0x3aa

**Comment by 1oid** [comment]
使用低版本的Chromium，推荐使用118版本。

可以在文档 [chromiumv118-下载](https://docs.ezreal.cool/docs/dowload#chromiumv118-%E4%B8%8B%E8%BD%BD) 中下载对应系统版本的Chromium

**Comment by 1oid** [comment]
下载完之后，解压并配置ez的`config.yaml`中的crawler相关部分
