### ISSUE TITLE
社区账号无法注册

### ISSUE THREAD

**Issue by winezer0** [m-sec-org/EZ#2]
社区账号无法注册，能不能发一个lic给我。

邮箱|手机接不到验证码， 解出来的图片数字也不能用

**Comment by zitn** [comment]
你好，邮箱/手机号验证码服务目前处于正常状态，请检查垃圾邮箱/垃圾短信查看。如遇短信发送报错，请附上报错截图，谢谢

**Comment by winezer0** [comment]
突然又可以了。

开始一直卡在这里

![image](https://github.com/m-sec-org/EZ/assets/46115146/6df8820d-c8a6-4166-a704-edfb9f8c7ccc)
