### ISSUE TITLE
开启爬虫错误

### ISSUE THREAD

**Issue by 1156494497** [m-sec-org/EZ#22]
每次开启爬虫就会报这个错误，请问是什么问题，之前使用mac端没遇到过这问题，在windows上用就会报错。
 2024/10/23 17:25 navigate timeout URL —— http://testphp.vulnweb.com/: context deadline exceeded
panic: json: cannot unmarshal object into Go struct field NetworkResponseReceivedExtraInfo.cookiePartitionKey of type string

goroutine 1715 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0x7ff6cba90d00?, 0xc009de1ae0?})
        github.com/go-rod/rod@v0.114.5/lib/utils/utils.go:68 +0x25
github.com/go-rod/rod/lib/utils.E(...)
        github.com/go-rod/rod@v0.114.5/lib/utils/utils.go:74
github.com/go-rod/rod.(*Message).Load(0xc008d62e40, {0x23c7ede95c0, 0xc004bf9c00})
        github.com/go-rod/rod@v0.114.5/utils.go:60 +0x26c
github.com/go-rod/rod.(*Browser).eachEvent.func1()
        github.com/go-rod/rod@v0.114.5/browser.go:397 +0x237
created by hawkX/pkg/engine.(*Page).HandleEventAndHijack
        hawkX@v0.0.0/pkg/engine/page.go:238 +0x3aa

**Comment by 1oid** [comment]
下载低于120版本的Chromium，推荐使用118的版本，然后配置config.yaml的crawler部分。

**Comment by 1156494497** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by 1156494497** [comment]
已解决
