### ISSUE TITLE
扫描总是自动退出

### ISSUE THREAD

**Issue by 6996299** [m-sec-org/EZ#23]
ubuntu后台运行nohup ./ez_linux_amd64 web & ，选择了所有模块，对十几个主域名和3000+urls进行扫描，总是任务启动不一会程序就自动退出
![image](https://github.com/user-attachments/assets/c0d0d349-f4bc-4182-bd59-f6d6ffcc4c3b)

**Comment by skr-rks** [comment]
win运行同样出现此问题。
![image](https://github.com/user-attachments/assets/991f60cd-f7e1-486d-a871-c6cc0ef7cb61)

**Comment by 1oid** [comment]
浏览器版本问题导致，在 [EZ文档](https://docs.ezreal.cool/docs/dowload) 处下载对应版本的Chromium并配置`config.yaml`的`crawler`部分

**Comment by skr-rks** [comment]
更换浏览器版本后已解决
