### ISSUE TITLE
SQL injection,XSS detection need some optimization 

### ISSUE THREAD

**Issue by khanjanny** [m-sec-org/EZ#3]
Hi there i was testing EZ performance, and it seems it have some great extra features for testing web applications or API whatever you say. although I tested EZ on different test applications like pikachu and it seems SQL injection,XSS is not yet properly implemented or are somehow missing detection of the vulnerability please take a look.

I was using you --listen option for pushing requests from burp to EZ.

**Comment by zitn** [comment]
Thank you very much for your comments, we have added the optimization suggestions you mentioned to the development plan, so please look forward to our future version.
