### ISSUE TITLE
all WRN

### ISSUE THREAD

**Issue by ysdxj** [m-sec-org/EZ#5]
[WRN] 2024-04-16 10:13:12 [distribute.go:513] get error: NOSCRIPT No matching script. Please use EVAL.
[WRN] 2024-04-16 10:13:12 [distribute.go:515] sleep 10 s to wait script hash
[WRN] 2024-04-16 10:13:12 [common.go:96] get error: NOSCRIPT No matching script. Please use EVAL.
[WRN] 2024-04-16 10:13:12 [common.go:98] sleep 10 s to wait script hash
[WRN] 2024-04-16 10:13:15 [common.go:96] get error: NOSCRIPT No matching script. Please use EVAL.
[WRN] 2024-04-16 10:13:15 [common.go:98] sleep 10 s to wait script hash
[WRN] 2024-04-16 10:13:15 [common.go:96] get error: NOSCRIPT No matching script. Please use EVAL.
[WRN] 2024-04-16 10:13:15 [common.go:98] sleep 10 s to wait script hash
[WRN] 2024-04-16 10:13:16 [common.go:96] get error: NOSCRIPT No matching script. Please use EVAL.
[WRN] 2024-04-16 10:13:16 [common.go:98] sleep 10 s to wait script hash
[WRN] 2024-04-16 10:13:17 [common.go:96] get error: NOSCRIPT No matching script. Please use EVAL.
[WRN] 2024-04-16 10:13:17 [common.go:98] sleep 10 s to wait script hash
[WRN] 2024-04-16 10:13:18 [common.go:96] get error: NOSCRIPT No matching script. Please use EVAL.
[WRN] 2024-04-16 10:13:18 [common.go:98] sleep 10 s to wait script hash
[WRN] 2024-04-16 10:13:19 [common.go:96] get error: NOSCRIPT No matching script. Please use EVAL.
[WRN] 2024-04-16 10:13:19 [common.go:96] get error: NOSCRIPT No matching script. Please use EVAL.
[WRN] 2024-04-16 10:13:19 [common.go:96] get error: NOSCRIPT No matching script. Please use EVAL.
[WRN] 2024-04-16 10:13:19 [common.go:98] sleep 10 s to wait script hash
[WRN] 2024-04-16 10:13:19 [common.go:98] sleep 10 s to wait script hash
[WRN] 2024-04-16 10:13:19 [common.go:98] sleep 10 s to wait script hash

**Comment by nodocx** [comment]
应该是配置过redis，然后redis进程挂掉过会出现这种情况，重新启动ez即可
