### ISSUE TITLE
为什么运行 1.8.8  版本报错了，作者大大给看看。

### ISSUE THREAD

**Issue by ss3931** [m-sec-org/EZ#6]
<img width="1030" alt="Snipaste_2024-04-23_17-31-53" src="https://github.com/m-sec-org/EZ/assets/75357260/2cf72f67-5775-4f7c-8bdc-bcbafab3f1f9">

运行web参数报错

**Comment by nodocx** [comment]
因新版配置文件结构有更新，请删除config.yaml文件后重新启动
