### ISSUE TITLE
配合EZ插件食用，在项目管理里，没有项目详情，是不是只有内部版ez才能联动ez游览器插件。

### ISSUE THREAD

**Issue by ss3931** [m-sec-org/EZ#7]

**Comment by 1oid** [comment]
看看是不是版本问题，我们只在最新版更新了这个功能，在release下载最新版。

**Comment by ss3931** [comment]
已下载最新版本 1.8.8 通过ez web 命令启动，项目管理模块内无项目详情，找不到token ，麻烦核实。



|
杨泽坤
内蒙古启明星辰信息安全技术有限公司
18647016236
***@***.***
010000
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年04月24日 10:17 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [m-sec-org/EZ] 配合EZ插件食用，在项目管理里，没有项目详情，是不是只有内部版ez才能联动ez游览器插件。 (Issue #7) |

看看是不是版本问题，我们只在最新版更新了这个功能，在release下载最新版。

**Comment by nodocx** [comment]
可能是因为静态页面没有更新导致，建议把1.8.8版本ez放在一个全新的文件夹然后启动
